<?php
return array (
  'home' => 
  array (
    'base' => 'http://cms24portfolio.s2310456027.student.kwmhgb.at/autogenerated-12',
    'languages' => 
    array (
      0 => 
      array (
        'title' => 'Deutsch',
        'enabled' => true,
        'languageId' => 0,
        'base' => '/',
        'locale' => 'de_DE',
        'navigationTitle' => 'English',
        'flag' => 'at',
        'hreflang' => 'de_DE',
        'websiteTitle' => '',
      ),
    ),
    'rootPageId' => 12,
    'websiteTitle' => '',
  ),
);
#